version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - "python"
      - "manage.py"
      - "runserver"
      - "0.0.0.0:3813"
    ports:
      - "8000:3813"
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
#        loki-url: http://host.docker.internal:3100/loki/api/v1/push

  grafana:
    image: grafana/grafana:9.5.8
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:2.8.4
    ports:
      - "3100:3100"
